### ISSUE TITLE
上课的时候打算用Spyder还是vscode?

### ISSUE THREAD

**Issue by WuShichao** [WuShichao/a-byte-of-python-bnu#4]
@henrysting 
书中第三章里的pycharm是换成Spyder还是vscode？

**Comment by WuShichao** [comment]
里面会用到Windows的命令行，其实Anaconda自带的Anaconda Prompt就可以完成cmd和PowellShell的操作，所以我用Anaconda Prompt替换了cmd。

**Comment by henrysting** [comment]
上课用cmd和编辑器，通用性较好， 各IDE仅作介绍。

**Comment by WuShichao** [comment]
@henrysting 
书中Windows安装部分，我当时没有把环境变量加到系统中，所以不能直接在cmd里使用，但是使用Anaconda Prompt没问题，而且具有cmd终端的功能。这个在书中我也做了强调。
书籍原稿中在介绍编辑器，着重介绍了PyCharm，我需不需要换成vscode？PyCharm其实属于IDE，而vscode属于通用型编辑器，我个人感觉可以在课上介绍vscode的使用，vscode配合其他插件同样可以完成其他程序语言的编写，用的人也很多。日常使用命令行vim和emacs来编程的人还是占少数，而且基本上都是高手：）

**Comment by henrysting** [comment]
机房机器上有什么用什么，Notepad++， emeditor，或者 scite 都可以， 只做编辑，功能越简单越好
